### ISSUE TITLE
Recruit in village has two entry points

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/Brytenwalda#5]
Either from the village menu or from the village elder, and they use a different code.

Make a single entry point to village recruitment, probably the best is via menu because it avoids loading the conversation scene.

**Comment by LordGolias** [comment]
The same is true for buying cattle.

**Comment by gdwitt** [comment]
Viking Conquest turned these into conversations for the initial encounter.
I think the intent is the same as guild masters: make the place hostile for strangers and easy once you are the village Lord. I personally would keep both, but check for a relation with the village greater than 10 to gain access to the quick menu. I will not be able to download any changes until Saturday due to delays from school work. I hope to post a revision on Sunday.

**Comment by LordGolias** [comment]
I personally don't like having two ways of doing the same thing, but I can live with it. If both are to be kept, it should be such that none of then is more advantageous, or if it is, it should be explicit why.

**Comment by gdwitt** [comment]
There really only should be on option from the viewpoint of the player. If one's relationship with the town is over 10 or 12, they can just walk up to a town and deal or recruit. There are really very few incentives to help out town elders and it's very easy to make them upset with no consequences. This isn't a must, but it's one of the few ways players are forced to help out villages and elders. If the code gets too complex, I would support other methods to stated goal.

**Comment by LordGolias** [comment]
I agree with you. Lets close this them and open an issue on making the recruit in town available only for relations higher than 10 or 12.
